export const state = () => ({
    selectfeature:[],
    features: [{
        "id": 2,
        "group": 1,
        "pattern": "EARTH PRO R-1",
        "featuresTitle": "",
        "featureDescription": "The 23 degree tread offers maximum traction while distinct terracing in the space between the lugs is designed to enhance self-cleaning and provide constant traction in soft soil and mud. The state-of theart neutral casing mould design minimizes stresses from the under inflated to the inflated tire, resulting in enhanced long-term reliability.",
      },
      {
        "id": 3,
        "group": 1,
        "pattern": "EARTH PRO R-1",
        "featuresTitle": "Applications",
        "featureDescription": "2WD Tractor",
      },
      {
        "id": 4,
        "group": 1,
        "pattern": "EARTH PRO R-1",
        "featuresTitle": "",
        "featureDescription": "MFWA Tractor",
      },
      {
        "id": 5,
        "group": 1,
        "pattern": "EARTH PRO 45",
        "featuresTitle": "",
        "featureDescription": "Optimized 45 degree lug angle ensures good road ability while on the road and superior self-cleaning in the field. Tire life is enhanced by compound designed for low wear, additional rubber at lug center, stabilized lugs at center by evenly distributed tie bar. Specially designed lug angles and radius prevents lug base cracks. Additional rubber layer improves penetration resistance. Tougher sidewall provides deflection stability and protection from external damages.",
      },
      {
        "id": 6,
        "group": 1,
        "pattern": "EARTH PRO 45",
        "featuresTitle": "Applications",
        "featureDescription": "2WD Tractor",
      },
      {
        "id": 7,
        "group": 1,
        "pattern": "EARTH PRO 45",
        "featuresTitle": "",
        "featureDescription": "MFWA Tractor",
      },
      {
        "id": 8,
        "group": 1,
        "pattern": "EARTH PRO F-2",
        "featuresTitle": "",
        "featureDescription": "Optimized rib design to achieve easy driving ON/OFF road application.",
      },
      {
        "id": 9,
        "group": 1,
        "pattern": "EARTH PRO F-2",
        "featuresTitle": "",
        "featureDescription": "Tire life enhancement by;",
      },
      {
        "id": 10,
        "group": 1,
        "pattern": "EARTH PRO F-2",
        "featuresTitle": "",
        "featureDescription": "Special compound designed for low wear",
      },
      {
        "id": 11,
        "group": 1,
        "pattern": "EARTH PRO F-2",
        "featuresTitle": "",
        "featureDescription": "Additional rubber at center rib.",
      },
      {
        "id": 12,
        "group": 1,
        "pattern": "EARTH PRO F-2",
        "featuresTitle": "",
        "featureDescription": "Specially designed RIB angles and radius for better road ability",
      },
      {
        "id": 13,
        "group": 1,
        "pattern": "EARTH PRO F-2",
        "featuresTitle": "",
        "featureDescription": "Improved sidewall deflection on loading for better stability",
      },
      {
        "id": 14,
        "group": 1,
        "pattern": "EARTH PRO F-2",
        "featuresTitle": "",
        "featureDescription": "Aesthetically improved modern F2 design with complete size range in Galaxy",
      },
      {
        "id": 15,
        "group": 1,
        "pattern": "EARTH PRO F-2",
        "featuresTitle": "",
        "featureDescription": "Additional rubber layer to provide under tread to improve penetration resistance",
      },
      {
        "id": 16,
        "group": 1,
        "pattern": "EARTH PRO F-2",
        "featuresTitle": "Applications",
        "featureDescription": "2WD Tractor",
      },
      {
        "id": 17,
        "group": 1,
        "pattern": "YARD MASTER ULTRA",
        "featuresTitle": "",
        "featureDescription": "Galaxy Yard Master Ultra is a premium service tire designed to operate in the most demanding conditions. Made of heavy duty construction that resists abrasions, punctures and impacts, the wide, flat tread profile provides excellent stability in forklift operations.",
      },
      {
        "id": 18,
        "group": 1,
        "pattern": "YARD MASTER ULTRA",
        "featuresTitle": "Applications",
        "featureDescription": "Forklift",
      },
      {
        "id": 19,
        "group": 1,
        "pattern": "YARD MASTER ULTRA",
        "featuresTitle": "",
        "featureDescription": "Heavy Duty Forklift",
      },
      {
        "id": 20,
        "group": 1,
        "pattern": "MARATHONER",
        "featuresTitle": "Extreme performance on rock with breakthrough cut resistance",
        "featureDescription": "The Marathoner is specifically designed to provide outstanding wear characteristics and offer great pulling power. The Marathoner features Galaxy’s Mud Breakers, designed to eject mud from the tread. They deliver the best high traction skid steer characteristics of any tire in the market. This combination has made the Marathoner one of the best skid steer tires in its class. This represents the making of a perfect tire for original equipment and aftermarket usage.",
      },
      {
        "id": 21,
        "group": 1,
        "pattern": "MARATHONER",
        "featuresTitle": "Applications",
        "featureDescription": "Backhoe",
      },
      {
        "id": 22,
        "group": 1,
        "pattern": "MARATHONER",
        "featuresTitle": "",
        "featureDescription": "Boomlift",
      },
      {
        "id": 23,
        "group": 1,
        "pattern": "MARATHONER",
        "featuresTitle": "",
        "featureDescription": "Compact Wheel Loader",
      },
      {
        "id": 24,
        "group": 1,
        "pattern": "MARATHONER",
        "featuresTitle": "",
        "featureDescription": "Skidsteer",
      },
      {
        "id": 25,
        "group": 1,
        "pattern": "MARATHONER",
        "featuresTitle": "",
        "featureDescription": "Utility Tractor",
      },
      {
        "id": 26,
        "group": 1,
        "pattern": "YARD MASTER SDS",
        "featuresTitle": "",
        "featureDescription": "The wide tire profile increases lateral load carrying capacity, stability traction. The large industrial block pattern increases life of the tread while promoting superior grip. Steel wire creel beads improve grip with rim and prevent rim slippage.",
      },
      {
        "id": 27,
        "group": 1,
        "pattern": "YARD MASTER SDS",
        "featuresTitle": "Applications",
        "featureDescription": "Forklift",
      },
      {
        "id": 28,
        "group": 1,
        "pattern": "PORT STAR PLUS",
        "featuresTitle": "Enjoy maximum comfort",
        "featureDescription": "Galaxy Port Star Plus has extra deep tread which is highest in this segment. This feature enables extra-long life and longer wear, providing better performance and more value for money.",
      },
      {
        "id": 29,
        "group": 1,
        "pattern": "PORT STAR PLUS",
        "featuresTitle": "Applications",
        "featureDescription": "Reach Stacker",
      },
      {
        "id": 30,
        "group": 1,
        "pattern": "PORT STAR 309",
        "featuresTitle": "Deflection ribs",
        "featureDescription": "A series of stacked deflection ribs protect the upper sidewall area against penetration by deflecting obstacles away from the tyre body.",
      },
      {
        "id": 31,
        "group": 1,
        "pattern": "PORT STAR 309",
        "featuresTitle": "",
        "featureDescription": "Alliance Portstar 309 is designed especially for heavy duty forklift trucks and container handlers operating on hard improved surfaces. Its unique tread design and special rubber compound provides long tread life. The heavy duty nylon construction protects the sidewalls against damage and ensures long tire life.",
      },
      {
        "id": 32,
        "group": 1,
        "pattern": "PORT STAR 309",
        "featuresTitle": "Applications",
        "featureDescription": "Container Handler",
      },
      {
        "id": 33,
        "group": 1,
        "pattern": "PORT STAR 309",
        "featuresTitle": "",
        "featureDescription": "Heavy Duty Forklift",
      },
      {
        "id": 34,
        "group": 1,
        "pattern": "HTSR 400",
        "featuresTitle": "",
        "featureDescription": "Low fuel consumption and high mileage.",
      },
      {
        "id": 35,
        "group": 1,
        "pattern": "HTSR 400",
        "featuresTitle": "",
        "featureDescription": "HTSR 400 is specially built for dump trucks that face extreme environments while hauling heavy loads. High tread depth ensures consistent traction and greater cut resistance making it the more productive choice. The presence of special compound ensures minimum heat build-up while performing longer runs. Superior cut &amp; chip protection with optimized belt design provides excellent durability resulting in reduced downtime.",
      },
      {
        "id": 36,
        "group": 1,
        "pattern": "HTSR 400",
        "featuresTitle": "Applications",
        "featureDescription": "Articulated Dump Truck",
      },
      {
        "id": 37,
        "group": 1,
        "pattern": "HTSR 400",
        "featuresTitle": "",
        "featureDescription": "Wheel Loader",
      },
      {
        "id": 38,
        "group": 1,
        "pattern": "MGSR 200",
        "featuresTitle": "",
        "featureDescription": "MGSR 200 is specially designed for grader applications. The unique tread pattern provides excellent traction and grip on uneven surfaces. Special compound formulation assures minimum heat-build up and maximum protection against damages. Sturdy construction with sidewall protector provides increased productivity and zero downtime making MGSR 200 the perfect choice as the partner for non-stop work.",
      },
      {
        "id": 39,
        "group": 1,
        "pattern": "MGSR 200",
        "featuresTitle": "Applications",
        "featureDescription": "Grader",
      },
      {
        "id": 40,
        "group": 1,
        "pattern": "EXR300",
        "featuresTitle": "",
        "featureDescription": "The Galaxy EXR 300 features an aggressive new tread design that delivers superior traction. Large, wide centre lugs provide excellent ground contact for maximum stability.",
      },
      {
        "id": 41,
        "group": 1,
        "pattern": "EXR300",
        "featuresTitle": "Applications",
        "featureDescription": "Articulated Dump Truck",
      },
      {
        "id": 42,
        "group": 1,
        "pattern": "EXR300",
        "featuresTitle": "",
        "featureDescription": "Wheel Loader",
      },
      {
        "id": 43,
        "group": 1,
        "pattern": "EXR300",
        "featuresTitle": "",
        "featureDescription": "Backhoe",
      },
      {
        "id": 44,
        "group": 1,
        "pattern": "EXR300",
        "featuresTitle": "",
        "featureDescription": "Dozer",
      },
      {
        "id": 45,
        "group": 1,
        "pattern": "INDUSRTRIAL R-1",
        "featuresTitle": "",
        "featureDescription": "This tire is designed for telescopic handlers and European backhoes used in agricultural applications. These tires provide extra traction in soft soil. In addition, the Rim Shield Protector adds to this tires durability. The Galaxy Industrial has earned a reputation around the world as a tire that outlasts the competition and provides reliable service.",
      },
      {
        "id": 46,
        "group": 1,
        "pattern": "INDUSRTRIAL R-1",
        "featuresTitle": "Applications",
        "featureDescription": "Industrial Tractor",
      },
      {
        "id": 47,
        "group": 1,
        "pattern": "INDUSRTRIAL R-1",
        "featuresTitle": "",
        "featureDescription": "Compact Wheel Loader",
      },
      {
        "id": 48,
        "group": 1,
        "pattern": "INDUSRTRIAL R-1",
        "featuresTitle": "",
        "featureDescription": "Backhoe",
      },
      {
        "id": 49,
        "group": 1,
        "pattern": "INDUSRTRIAL R-1",
        "featuresTitle": "",
        "featureDescription": "Telehander",
      },
      {
        "id": 50,
        "group": 1,
        "pattern": "INDUSRTRIAL R-1",
        "featuresTitle": "",
        "featureDescription": "Utility Tractor",
      },
      {
        "id": 51,
        "group": 1,
        "pattern": "SUPER INDUSRTRIAL LUG",
        "featuresTitle": "Galaxy Super Industrial Lug is a classic, well accepted design built with more plies than other R-4 tires providing superior strength and longer treads life. The cleat is solid in the center for wear and penetration protection. The design of this tire has won it the distinction of being selected by several Original Equipment manufacturers.",
      },
      {
        "id": 52,
        "group": 1,
        "pattern": "SUPER INDUSRTRIAL LUG",
        "featuresTitle": "Applications",
        "featureDescription": "Industrial Tractor",
      },
      {
        "id": 53,
        "group": 1,
        "pattern": "SUPER INDUSRTRIAL LUG",
        "featuresTitle": "Safety",
        "featureDescription": "Compact Wheel Loader",
      },
      {
        "id": 54,
        "group": 1,
        "pattern": "SUPER INDUSRTRIAL LUG",
        "featuresTitle": "",
        "featureDescription": "Backhoe",
      },
      {
        "id": 55,
        "group": 1,
        "pattern": "SUPER INDUSRTRIAL LUG",
        "featuresTitle": "",
        "featureDescription": "Utility Tractor",
      },
      {
        "id": 56,
        "group": 1,
        "pattern": "MULTI TOUGH",
        "featuresTitle": "Your access to any adventure",
        "featureDescription": "This radial tire is used for mixed application on hard surfaces and soft soil. The unique non-directional tread design is ideal for on and off-the-road service and facilitates easier self-cleaning. High mileage, best traction, fuel saving and ride comfort are some of the tires advantages.",
      },
      {
        "id": 57,
        "group": 1,
        "pattern": "MULTI TOUGH",
        "featuresTitle": "Applications",
        "featureDescription": "Compact Wheel Loader",
      },
      {
        "id": 58,
        "group": 1,
        "pattern": "MULTI TOUGH",
        "featuresTitle": "",
        "featureDescription": "Backhoe",
      },
      {
        "id": 59,
        "group": 1,
        "pattern": "MULTI TOUGH",
        "featuresTitle": "",
        "featureDescription": "Telehander",
      },
      {
        "id": 60,
        "group": 1,
        "pattern": "MULTI TOUGH",
        "featuresTitle": "",
        "featureDescription": "Utility Tractor",
      },
      {
        "id": 61,
        "group": 1,
        "pattern": "HM400S",
        "featuresTitle": "",
        "featureDescription": "Galaxy HM 400S is an extra-deep, smooth treaded tire for port applications. Abrasion resistant tread compound and large contact area ensure long life. The strong casing and high number of plies provide superior lateral stability and a high load carrying capacity.",
      },
      {
        "id": 62,
        "group": 1,
        "pattern": "HM400S",
        "featuresTitle": "Applications",
        "featureDescription": "Reach Stacker",
      },
      {
        "id": 63,
        "group": 1,
        "pattern": "AGRI TRAC II",
        "featuresTitle": "",
        "featureDescription": "The Galaxy Agri-Trac II has a modern, curved 45 degree lug design for both smooth riding on the road, and excellent traction in all field conditions. Its special stepped surfaces between lugs facilitate cleaning in very muddy conditions. The wide nose bar provides extra life on hard surfaces/roading. The Agri Trac II has been reinforced with a wear resistant compound to give it long wear capabilities. The Agri Trac II has been selected as an OEM fitment tire by leading tractor manufacturers.",
      },
      {
        "id": 64,
        "group": 1,
        "pattern": "AGRI TRAC II",
        "featuresTitle": "Applications",
        "featureDescription": "2WD Tractor",
      },
      {
        "id": 65,
        "group": 1,
        "pattern": "AGRI TRAC II",
        "featuresTitle": "",
        "featureDescription": "MFWA Tractor",
      },
      {
        "id": 66,
        "group": 1,
        "pattern": "MPC",
        "featuresTitle": "",
        "featureDescription": "The Galaxy MPC is a first of its kind economical tire developed for telehandlers and grader-loader applications. The design provides optimal traction and heat and cut resistance for all types of grader-loader application. The design features also ensure excellent self-cleaning characteristics and long life.",
      },
      {
        "id": 67,
        "group": 1,
        "pattern": "MPC",
        "featuresTitle": "Applications",
        "featureDescription": "Grader",
      },






      {
        "id": 67,
        "group": 1,
        "pattern": "LDSR 300",
        "featuresTitle": "LDSR 300",
        "featureDescription": "",
      },
      {
        "id": 67,
        "group": 1,
        "pattern": "LDSR 300",
        "featuresTitle": "",
        "featureDescription": "LDSR 300 is specially constructed for wheel loaders operating in the toughest environments. Transportation of heavy load demands excellent stability and robustness. Sturdy radial construction coupled with strong sidewall protector provides LDSR 300 superior strength and endurance to withstand challenging terrains. Premium tread compounds provide excellent protection against lug-tearing and chunking, helping the machine to perform efficiently without any downtime. “S-shaped” tread pattern with stepped lugs ensure optimal traction and enhanced self–cleaning assuring high productivity.",
      },
      {
        "id": 67,
        "group": 1,
        "pattern": "LDSR 300",
        "featuresTitle": "Applications",
        "featureDescription": "",
      },
      {
        "id": 67,
        "group": 1,
        "pattern": "LDSR 300",
        "featuresTitle": "",
        "featureDescription": "Wheel Loader",
      },
    ]
})

export const getters = {
    selectfeature (state){
        return state.selectfeature
    }
}

export const mutations = {
    SET_SELECT_PATTERN_FEATURE (state, pattern) {
        for (var item, i = 0; item = state.features[i++];) {
            if (pattern == item.pattern) {
                state.selectfeature.push(item);
            }
        }
    },
    SET_CLEAR_FEATURE_SELECTION (state, data) {
        state.selectfeature = data
    },
}

export const actions = {
    async setSelectPattaern ({ commit }, pattern) {
        commit('SET_SELECT_PATTERN_FEATURE', pattern)
    },
    clearSelectFeaturs ({ commit }) {
        commit('SET_CLEAR_FEATURE_SELECTION', [])
    },
}