export const state = () => ({
    selectfeature:[],
    features: [{
        "id": 2,
        "group": 1,
        "pattern": "GRABBER AT",
        "featuresTitle": "Off-road feeling in a new dimension",
        "featureDescription": "Outstanding traction and excellent steering performance off-road",
      },
      {
        "id": 3,
        "group": 1,
        "pattern": "GRABBER AT",
        "featuresTitle": "",
        "featureDescription": "High grip in muddy terrain",
      },
      {
        "id": 4,
        "group": 1,
        "pattern": "GRABBER AT",
        "featuresTitle": "",
        "featureDescription": "Long lasting in rough conditions",
      },
      {
        "id": 5,
        "group": 1,
        "pattern": "GRABBER AT",
        "featuresTitle": "",
        "featureDescription": "High comfort and low riding noise.",
      },
      {
        "id": 6,
        "group": 1,
        "pattern": "GRABBER AT",
        "featuresTitle": "",
        "featureDescription": "Robust tread pattern even in rough terrain.",
      },
      {
        "id": 7,
        "group": 1,
        "pattern": "GRABBER AT",
        "featuresTitle": "",
        "featureDescription": "Best aquaplaning performance.",
      },
      {
        "id": 8,
        "group": 1,
        "pattern": "GRABBER AT",
        "featuresTitle": "Outstanding traction and excellent steering performance off-road.",
        "featureDescription": "The Grabber AT transfers the forces from the engine so directly that both the off-road and steering response are outstanding.",
      },
      {
        "id": 9,
        "group": 1,
        "pattern": "GRABBER AT",
        "featuresTitle": "High grip in muddy terrain",
        "featureDescription": "The tire is able to clean itself. This means the Grabber AT always grips extremely well on muddy terrain.",
      },
      {
        "id": 10,
        "group": 1,
        "pattern": "GRABBER AT",
        "featuresTitle": "Robust tread pattern even in rough terrain",
        "featureDescription": "In order to achieve optimum transfer o forces the tyre is very rigid and yet flexible enough to prevent cuts and chips. Even under harsh conditions the tyre remains robust.",
      },
      {
        "id": 11,
        "group": 1,
        "pattern": "GRABBER AT",
        "featuresTitle": "Long lasting rough conditions",
        "featureDescription": "The tread design prevents stones from getting in the tread. The tyre is durable even when put under heavy strain on rough terrain.",
      },
      {
        "id": 12,
        "group": 1,
        "pattern": "GRABBER AT",
        "featuresTitle": "Quiet and comfortable",
        "featureDescription": "The road noise is pleasantly quiet and the tire runs comfortable over the ground",
      },
      {
        "id": 13,
        "group": 1,
        "pattern": "GRABBER AT",
        "featuresTitle": "High protection against aquaplaning",
        "featureDescription": "Grooves and sipes channel water from the tread and minimize the aquaplaning risk.",
      },
      {
        "id": 14,
        "group": 1,
        "pattern": "GRABBER X3",
        "featuresTitle": "Conquer your terrain",
        "featureDescription": "General Tire’s new mud terrain tyre delivers outstanding off-road performance, coupled with good street manners. The GRABBER X3 offers aggressive styling and is engineered for durability, with innovative tread features. 20:80 on/off",
      },
      {
        "id": 15,
        "group": 1,
        "pattern": "GRABBER X3",
        "featuresTitle": "",
        "featureDescription": "Experience exceptional grip",
      },
      {
        "id": 16,
        "group": 1,
        "pattern": "GRABBER X3",
        "featuresTitle": "",
        "featureDescription": "Go off-road with confidence",
      },
      {
        "id": 17,
        "group": 1,
        "pattern": "GRABBER X3",
        "featuresTitle": "",
        "featureDescription": "Enjoy maximum comfort",
      },
      {
        "id": 18,
        "group": 1,
        "pattern": "GRABBER X3",
        "featuresTitle": "Extreme performance in mud",
        "featureDescription": "Enjoy extreme off-road maneuvers with aggressive and open pattern design that grips extremely well in muddy terrain. Evacuation channels ensure quick and efficient self-cleaning action.",
      },
      {
        "id": 19,
        "group": 1,
        "pattern": "GRABBER X3",
        "featuresTitle": "Extreme performance in dirt with superior grip.",
        "featureDescription": "Experience superior grip on firm, lose or boggy ground with innovative tread design that provides additional biting edges. Stone bumpers protect the tyre and minimize stone drilling for log lasting off-road fun.",
      },
      {
        "id": 20,
        "group": 1,
        "pattern": "GRABBER X3",
        "featuresTitle": "Extreme performance on rock with breakthrough cut resistance",
        "featureDescription": "Conquer with confidence: the exceptionally robust and durable tyre remains vigorous even in harshest conditions. Master extreme off-roading with excellent grip and strong sidewall protection",
      },
      {
        "id": 21,
        "group": 1,
        "pattern": "GRABBER X3",
        "featuresTitle": "Duragen technology",
        "featureDescription": "Three ply constructions on all sizes provide race proven durability and puncture resistance. Robust compound gives excellent cut and chip resistance. Ultra high strength steel belts ensure even footprint for confident stability",
      },
      {
        "id": 22,
        "group": 1,
        "pattern": "GRABBER X3",
        "featuresTitle": "Your access to any adventure",
        "featureDescription": "The all-terrain tyre developed to meet the needs of SUV, pick-up truck and off-road vehicle drivers who want a combination of exceptional off-road capabilities and confident on-road manners. 50:50 on/off",
      },
      {
        "id": 23,
        "group": 1,
        "pattern": "GRABBER X3",
        "featuresTitle": "",
        "featureDescription": "EXTREME performance in MUD with engineered tread features",
      },
      {
        "id": 24,
        "group": 1,
        "pattern": "GRABBER X3",
        "featuresTitle": "",
        "featureDescription": "EXTREME performance in DIRT with superior grip",
      },
      {
        "id": 25,
        "group": 1,
        "pattern": "GRABBER X3",
        "featuresTitle": "",
        "featureDescription": "EXTREME performance on ROCK with breakthrough cut resistance",
      },
      {
        "id": 26,
        "group": 1,
        "pattern": "GRABBER X3",
        "featuresTitle": "Experience exceptional grip",
        "featureDescription": "Innovative pattern design achieves exceptional off-road grip through gripping edges that interlock with loose surfaces. The open tread shoulder ensures efficient self-cleaning action for added traction in mud",
      },
      {
        "id": 27,
        "group": 1,
        "pattern": "GRABBER X3",
        "featuresTitle": "Go off road with confidence",
        "featureDescription": "Tread with robust compound and reinforced blocks ensures a long tyre life even in rugged terrain. Moreover, it delivers confident stability with ultra-high-strength steel belts.",
      },
      {
        "id": 28,
        "group": 1,
        "pattern": "GRABBER X3",
        "featuresTitle": "Enjoy maximum comfort",
        "featureDescription": "Uniform block geometry for an even material distribution and optimized tread block orientation for a smooth interaction with the surface: both features allow a considerably comfortable and pleasant on-road drive in an all-terrain tyre line",
      },
      {
        "id": 29,
        "group": 1,
        "pattern": "GRABBER X3",
        "featuresTitle": "Sidewall lugs",
        "featureDescription": "large sidewall lugs on the upper sidewall protect the tyre body from stones, rocks and debris.",
      },
      {
        "id": 30,
        "group": 1,
        "pattern": "GRABBER X3",
        "featuresTitle": "Deflection ribs",
        "featureDescription": "A series of stacked deflection ribs protect the upper sidewall area against penetration by deflecting obstacles away from the tyre body.",
      },
      {
        "id": 31,
        "group": 1,
        "pattern": "GRABBER X3",
        "featuresTitle": "Rim protection rib",
        "featureDescription": "Rim protection rib shields the tyre and wheel bead area from damage caused by curbstones and off-road obstacles.",
      },
      {
        "id": 32,
        "group": 1,
        "pattern": "ALTIMAX COMFORT",
        "featuresTitle": "Benefits",
        "featureDescription": "Shorter braking distance.",
      },
      {
        "id": 33,
        "group": 1,
        "pattern": "ALTIMAX COMFORT",
        "featuresTitle": "",
        "featureDescription": "Very good steering response on wet roads and low risk of Aquaplaning.",
      },
      {
        "id": 34,
        "group": 1,
        "pattern": "ALTIMAX COMFORT",
        "featuresTitle": "",
        "featureDescription": "Low fuel consumption and high mileage.",
      },
      {
        "id": 35,
        "group": 1,
        "pattern": "ALTIMAX COMFORT",
        "featuresTitle": "",
        "featureDescription": "Visual Alignment Indicator: Increased mileage potential through avoidance of premature removal due to irregular wear.",
      },
      {
        "id": 36,
        "group": 1,
        "pattern": "ALTIMAX COMFORT",
        "featuresTitle": "",
        "featureDescription": "Replacement Tire Monitor: Improved safety and optimal tire performance.",
      },
      {
        "id": 37,
        "group": 1,
        "pattern": "ALTIMAX COMFORT",
        "featuresTitle": "Braking",
        "featureDescription": "Shorter braking distance;",
      },
      {
        "id": 38,
        "group": 1,
        "pattern": "ALTIMAX COMFORT",
        "featuresTitle": "",
        "featureDescription": "The Altimax Comfort has outstanding handling characteristics in wet conditions, as the tire displaces the water from the tread. This also ensures shorter braking distances.",
      },
      {
        "id": 39,
        "group": 1,
        "pattern": "ALTIMAX COMFORT",
        "featuresTitle": "Steering response and aquaplaning",
        "featureDescription": "Very good steering response on wet roads and low risk of aquaplaning; The right tread gives the vehicle high degree of stability on wet surfaces. This means the steering performance always remains precise, even in wet conditions, and the risk of aquaplaning is minimized.",
      },
      {
        "id": 40,
        "group": 1,
        "pattern": "ALTIMAX COMFORT",
        "featuresTitle": "Fuel consumption and mileage",
        "featureDescription": "Low fuel consumption and high mileage; the tread compound minimizes rolling resistance. This keeps fuel consumption low and increases mileage..",
      },
      {
        "id": 41,
        "group": 1,
        "pattern": "ALTIMAX COMFORT",
        "featuresTitle": "Visual alignment indicator",
        "featureDescription": "Visual alignment indicator signals incorrect alignment; if the tread wears unevenly over the first 1,000 kilometers the visual alignment indicator technology (VIA) signals this to the user. This significantly extends the service life of the tire.",
      },
      {
        "id": 42,
        "group": 1,
        "pattern": "ALTIMAX COMFORT",
        "featuresTitle": "",
        "featureDescription": "The Altimax Comfort has outstanding handling characteristics in wet conditions, as the tire displaces the water from the tread. This also ensures shorter braking distances.",
      },
      {
        "id": 43,
        "group": 1,
        "pattern": "ALTIMAX COMFORT",
        "featuresTitle": "RTM- Replacement Tire Monitor for greater safety",
        "featureDescription": "RTM technology tels the driver in good time when a tyre change is due, which increases safety.",
      },
      {
        "id": 44,
        "group": 1,
        "pattern": "ALTIMAX SPORT",
        "featuresTitle": "The Alticmax Sport guarantees precise steering response when cornering.",
        "featureDescription": "Precise steering response and safe driving on curvy roads.",
      },
      {
        "id": 45,
        "group": 1,
        "pattern": "ALTIMAX SPORT",
        "featuresTitle": "",
        "featureDescription": "Shorter braking distance",
      },
      {
        "id": 46,
        "group": 1,
        "pattern": "ALTIMAX SPORT",
        "featuresTitle": "",
        "featureDescription": "Low fuel consumption and high mileage",
      },
      {
        "id": 47,
        "group": 1,
        "pattern": "ALTIMAX SPORT",
        "featuresTitle": "",
        "featureDescription": "Visual Alignment Indicator: Increased mileage potential through avoidance of premature removal due to irregular wear",
      },
      {
        "id": 48,
        "group": 1,
        "pattern": "ALTIMAX SPORT",
        "featuresTitle": "",
        "featureDescription": "Replacement Tire Monitor: Improved safety and optimal tyre performance",
      },
      {
        "id": 49,
        "group": 1,
        "pattern": "ALTIMAX SPORT",
        "featuresTitle": "Safety",
        "featureDescription": "Precise steering response and safe driving on curvy roads. The rigidity and optimum stability of the tire means the steering response is always precise- for safe driving even on winding roads.",
      },
      {
        "id": 50,
        "group": 1,
        "pattern": "ALTIMAX SPORT",
        "featuresTitle": "Braking",
        "featureDescription": "Shorter braking distance on wet roads; In the rain the tread of the Altimax Sport quickly displaces the water from the tire contact area, shortening the braking distance.",
      },
      {
        "id": 51,
        "group": 1,
        "pattern": "ALTIMAX SPORT",
        "featuresTitle": "Fuel consumption and mileage",
        "featureDescription": "Low fuel consumption and high mileage. In order to achieve both good performance in wet conditions and low rolling resistance, the innovative silica compound ensures low fuel consumption and high mileage.",
      },
      {
        "id": 52,
        "group": 1,
        "pattern": "ALTIMAX SPORT",
        "featuresTitle": "Visual alignment indicator",
        "featureDescription": "VAI signals incorrect alignment. If the tread wears unevenly over the first 1,000 kilometers, the Visual Alignment indicator technology signals this to the user. This significantly extends service life of the tyre.",
      },
      {
        "id": 53,
        "group": 1,
        "pattern": "ALTIMAX SPORT",
        "featuresTitle": "Safety",
        "featureDescription": "RTM- Replacement Tire Monitor for greater safety. RTM technology tels the driver in good time when a tyre change is due, which increases safety.",
      },
      {
        "id": 54,
        "group": 1,
        "pattern": "ALTIMAX SPORT",
        "featuresTitle": "",
        "featureDescription": "Shorter braking distance",
      },
      {
        "id": 55,
        "group": 1,
        "pattern": "ALTIMAX SPORT",
        "featuresTitle": "",
        "featureDescription": "Shorter braking distance",
      },
      {
        "id": 56,
        "group": 1,
        "pattern": "GRABBER AT3",
        "featuresTitle": "Your access to any adventure",
        "featureDescription": "The all-terrain tyre developed to meet the needs of SUV, pick-up truck and off-road vehicle drivers who want a combination of exceptional off-road capabilities and confident on-road manners.",
      },
      {
        "id": 57,
        "group": 1,
        "pattern": "GRABBER AT3",
        "featuresTitle": "50:50 on/off",
        "featureDescription": "Experience exceptional grip",
      },
      {
        "id": 58,
        "group": 1,
        "pattern": "GRABBER AT3",
        "featuresTitle": "",
        "featureDescription": "Go off-road with confidence",
      },
      {
        "id": 59,
        "group": 1,
        "pattern": "GRABBER AT3",
        "featuresTitle": "",
        "featureDescription": "Enjoy maximum comfort",
      },
      {
        "id": 60,
        "group": 1,
        "pattern": "GRABBER AT3",
        "featuresTitle": "Experience exceptional grip",
        "featureDescription": "Innovative pattern design achieves exceptional off-road grip through gripping edges that interlock with loose surfaces. The open tread shoulder ensures efficient self-cleaning action for added traction in mud",
      },
      {
        "id": 61,
        "group": 1,
        "pattern": "GRABBER AT3",
        "featuresTitle": "Go off road with confidence",
        "featureDescription": "Tread with robust compound and reinforced blocks ensures a long tyre life even in rugged terrain. Moreover, it delivers confident stability with ultra-high-strength steel belts.",
      },
      {
        "id": 62,
        "group": 1,
        "pattern": "GRABBER AT3",
        "featuresTitle": "Enjoy maximum comfort",
        "featureDescription": "Uniform block geometry for an even material distribution and optimized tread block orientation for a smooth interaction with the surface: both features allow a considerably comfortable and pleasant on-road drive in an all-terrain tyre line",
      },
      {
        "id": 63,
        "group": 1,
        "pattern": "GRABBER AT3",
        "featuresTitle": "SIDEWALL FEATURES.",
        "featureDescription": "Large sidewall lugs on the upper sidewall protect the tyre body from stones, rocks and debris.",
      },
      {
        "id": 64,
        "group": 1,
        "pattern": "GRABBER AT3",
        "featuresTitle": "Deflection ribs:",
        "featureDescription": "A series of stacked deflection ribs protect the upper sidewall area against penetration by deflecting obstacles away from the tyre body.",
      },
      {
        "id": 65,
        "group": 1,
        "pattern": "GRABBER AT3",
        "featuresTitle": "Rim protection rib:",
        "featureDescription": "Rim protection rib shields the tyre and wheel bead area from damage caused by curbstones and off-road obstacles.",
      },
      {
        "id": 66,
        "group": 1,
        "pattern": "ALTIMAX COMFORT",
        "featuresTitle": "A reliable partner for a comfortable quiet ride",
        "featureDescription": "Shorter braking distance",
      },
      {
        "id": 67,
        "group": 1,
        "pattern": "ALTIMAX COMFORT",
        "featuresTitle": "",
        "featureDescription": "Very good steering response on wet roads and low risk of Aquaplaning",
      },
      {
        "id": 68,
        "group": 1,
        "pattern": "ALTIMAX COMFORT",
        "featuresTitle": "",
        "featureDescription": "Low fuel consumption and high mileage",
      },
      {
        "id": 69,
        "group": 1,
        "pattern": "ALTIMAX COMFORT",
        "featuresTitle": "",
        "featureDescription": "Visual Alignment Indicator: Increased mileage potential through avoidance of premature removal due to irregular wear",
      },
      {
        "id": 70,
        "group": 1,
        "pattern": "ALTIMAX COMFORT",
        "featuresTitle": "",
        "featureDescription": "Replacement Tire Monitor: Improved safety and optimal tire performance",
      },
      {
        "id": 71,
        "group": 1,
        "pattern": "ALTIMAX COMFORT",
        "featuresTitle": "TECHNICAL DETAILS",
        "featureDescription": "Shorter braking distance;",
      },
      {
        "id": 72,
        "group": 1,
        "pattern": "ALTIMAX COMFORT",
        "featuresTitle": "",
        "featureDescription": "The Altimax Comfort has outstanding handling characteristics in wet conditions, as the tire displaces the water from the tread. This also ensures shorter braking distances.",
      },
      {
        "id": 73,
        "group": 1,
        "pattern": "ALTIMAX COMFORT",
        "featuresTitle": "Steering response and aquaplaning:",
        "featureDescription": "Very good steering response on wet roads and low risk of aquaplaning;",
      },
      {
        "id": 74,
        "group": 1,
        "pattern": "ALTIMAX COMFORT",
        "featuresTitle": "",
        "featureDescription": "The right tread gives the vehicle high degree of stability on wet surfaces. This means the steering performance always remains precise, even in wet conditions, and the risk of aquaplaning is minimized.",
      },
      {
        "id": 75,
        "group": 1,
        "pattern": "ALTIMAX COMFORT",
        "featuresTitle": "Fuel consumption and mileage:",
        "featureDescription": "Low fuel consumption and high mileage; the tread compound minimizes rolling resistance. This keeps fuel consumption low and increases mileage..",
      },
      {
        "id": 76,
        "group": 1,
        "pattern": "ALTIMAX COMFORT",
        "featuresTitle": "Visual alignment indicator:",
        "featureDescription": "Visual alignment indicator signals incorrect alignment; if the tread wears unevenly over the first 1,000 kilometers the visual alignment indicator technology (VIA) signals this to the user. This significantly extends the service life of the tire.",
      },
      {
        "id": 77,
        "group": 1,
        "pattern": "ALTIMAX COMFORT",
        "featuresTitle": "RTM- Replacement Tire Monitor for greater safety.",
        "featureDescription": "RTM technology tels the driver in good time when a tyre change is due, which increases safety.",
      },
      {
        "id": 78,
        "group": 1,
        "pattern": "ALTIMAX SPORT",
        "featuresTitle": "The Alticmax Sport guarantees precise steering response when cornering.",
        "featureDescription": "Precise steering response and safe driving on curvy roads",
      },
      {
        "id": 79,
        "group": 1,
        "pattern": "ALTIMAX SPORT",
        "featuresTitle": "",
        "featureDescription": "Shorter braking distance",
      },
      {
        "id": 80,
        "group": 1,
        "pattern": "ALTIMAX SPORT",
        "featuresTitle": "",
        "featureDescription": "Low fuel consumption and high mileage",
      },
      {
        "id": 81,
        "group": 1,
        "pattern": "ALTIMAX SPORT",
        "featuresTitle": "",
        "featureDescription": "Visual Alignment Indicator: Increased mileage potential through avoidance of premature removal due to irregular wear",
      },
      {
        "id": 82,
        "group": 1,
        "pattern": "ALTIMAX SPORT",
        "featuresTitle": "",
        "featureDescription": "Replacement Tire Monitor: Improved safety and optimal tyre performance",
      },
      {
        "id": 83,
        "group": 1,
        "pattern": "ALTIMAX SPORT",
        "featuresTitle": "TECHNICAL DETAILS",
        "featureDescription": "Precise steering response and safe driving on curvy roads The rigidity and optimum stability of the tire means the steering response is always precise- for safe driving even on winding roads.",
      },
      {
        "id": 84,
        "group": 1,
        "pattern": "ALTIMAX SPORT",
        "featuresTitle": "Braking:",
        "featureDescription": "",
      },
      {
        "id": 85,
        "group": 1,
        "pattern": "ALTIMAX SPORT",
        "featuresTitle": "Shorter braking distance on wet roads;",
        "featureDescription": "In the rain the tread of the Altimax Sport quickly displaces the water from the tire contact area, shortening the braking distance.",
      },
      {
        "id": 86,
        "group": 1,
        "pattern": "ALTIMAX SPORT",
        "featuresTitle": "Fuel consumption and mileage",
        "featureDescription": "Low fuel consumption and high mileage",
      },
      {
        "id": 87,
        "group": 1,
        "pattern": "ALTIMAX SPORT",
        "featuresTitle": "",
        "featureDescription": "In order to achieve both good performance in wet conditions and low rolling resistance, the innovative silica compound ensures low fuel consumption and high mileage.",
      },
      {
        "id": 88,
        "group": 1,
        "pattern": "ALTIMAX SPORT",
        "featuresTitle": "Visual alignment indicator",
        "featureDescription": "VAI signals incorrect alignment.",
      },
      {
        "id": 89,
        "group": 1,
        "pattern": "ALTIMAX SPORT",
        "featuresTitle": "",
        "featureDescription": "If the tread wears unevenly over the first 1,000 kilometers, the Visual Alignment indicator technology signals this to the user. This significantly extends service life of the tyre.",
      },
      {
        "id": 90,
        "group": 1,
        "pattern": "ALTIMAX SPORT",
        "featuresTitle": "Safety",
        "featureDescription": "RTM- Replacement Tire Monitor for greater safety.",
      },
      {
        "id": 91,
        "group": 1,
        "pattern": "ALTIMAX SPORT",
        "featuresTitle": "",
        "featureDescription": "RTM technology tels the driver in good time when a tyre change is due, which increases safety",
      },
      {
        "id": 92,
        "group": 1,
        "pattern": "GRABBER GT",
        "featuresTitle": "Is not just really good to look at",
        "featureDescription": "Newly developed for high-powered SUVs, the Grabber GT is not just really good to look at.",
      },
      {
        "id": 93,
        "group": 1,
        "pattern": "ALTIMAX SPORT",
        "featuresTitle": "",
        "featureDescription": "High driving comfort due to reduced noise level",
      },
      {
        "id": 94,
        "group": 1,
        "pattern": "ALTIMAX SPORT",
        "featuresTitle": "",
        "featureDescription": "Excellent wet braking performance",
      },
      {
        "id": 95,
        "group": 1,
        "pattern": "ALTIMAX SPORT",
        "featuresTitle": "",
        "featureDescription": "Visual Alignment Indicator: Increased mileage potential through avoidance of premature removal due to irregular wear",
      },
      {
        "id": 96,
        "group": 1,
        "pattern": "ALTIMAX SPORT",
        "featuresTitle": "",
        "featureDescription": "Replacement Tire Monitor: Improved safety and optimal tyre performance",
      },
      {
        "id": 97,
        "group": 1,
        "pattern": "ALTIMAX SPORT",
        "featuresTitle": "TECHNICAL DETAILS",
        "featureDescription": "",
      },
      {
        "id": 98,
        "group": 1,
        "pattern": "ALTIMAX SPORT",
        "featuresTitle": "Performance;",
        "featureDescription": "The Grabber GT has a high degree of rigidity and a well-balanced tread structure. This ensures excellent handling on dry and wet roads.",
      },
      {
        "id": 99,
        "group": 1,
        "pattern": "ALTIMAX SPORT",
        "featuresTitle": "Comfort;",
        "featureDescription": "High driving comfort due to reduced noise level",
      },
      {
        "id": 100,
        "group": 1,
        "pattern": "ALTIMAX SPORT",
        "featuresTitle": "",
        "featureDescription": "The robust tread minimizes wear. Throughout the service life of the tyre it provides a comfortable ride and noise level is low.",
      },
      {
        "id": 101,
        "group": 1,
        "pattern": "ALTIMAX SPORT",
        "featuresTitle": "Performance;",
        "featureDescription": "Excellent wet braking performance",
      },
      {
        "id": 102,
        "group": 1,
        "pattern": "ALTIMAX SPORT",
        "featuresTitle": ";",
        "featureDescription": "A lot of gripping edges provide a very high level of safety because of excellent grip in the wet even when braking.",
      },
      {
        "id": 103,
        "group": 1,
        "pattern": "ALTIMAX SPORT",
        "featuresTitle": "Visual Alignment Indicator",
        "featureDescription": "VAI signals incorrect alignment.",
      },
      {
        "id": 104,
        "group": 1,
        "pattern": "ALTIMAX SPORT",
        "featuresTitle": "",
        "featureDescription": "If the tread wears unevenly over the first 1,000 kilometers, the Visual Alignment indicator technology signals this to the user. This significantly extends service life of the tyre.",
      },
      {
        "id": 105,
        "group": 1,
        "pattern": "ALTIMAX SPORT",
        "featuresTitle": "Safety",
        "featureDescription": "RTM- Replacement Tire Monitor for greater safety.",
      },
      {
        "id": 106,
        "group": 1,
        "pattern": "ALTIMAX SPORT",
        "featuresTitle": "",
        "featureDescription": "RTM technology tels the driver in good time when a tyre change is due, which increases safety",
      },
      {
        "id": 107,
        "group": 1,
        "pattern": "GRABBER GT",
        "featuresTitle": "Is not just really good to look at;",
        "featureDescription": "Newly developed for high-powered SUVs, the Grabber GT is not just really good to look at.",
      },
      {
        "id": 108,
        "group": 1,
        "pattern": "GRABBER GT",
        "featuresTitle": "100:0 on/off",
        "featureDescription": "Outstanding handling performance on dry and wet roads",
      },
      {
        "id": 109,
        "group": 1,
        "pattern": "GRABBER GT",
        "featuresTitle": "100:0 on/off",
        "featureDescription": "Outstanding handling performance on dry and wet roads",
      },
      {
        "id": 110,
        "group": 1,
        "pattern": "GRABBER GT",
        "featuresTitle": "",
        "featureDescription": "Excellent wet braking performance",
      },
      {
        "id": 111,
        "group": 1,
        "pattern": "GRABBER GT",
        "featuresTitle": "",
        "featureDescription": "Visual Alignment Indicator: Increased mileage potential through avoidance of premature removal due to irregular wear",
      },
      {
        "id": 112,
        "group": 1,
        "pattern": "GRABBER GT",
        "featuresTitle": "",
        "featureDescription": "Replacement Tire Monitor: Improved safety and optimal tyre performance",
      },
      {
        "id": 108,
        "group": 1,
        "pattern": "GRABBER GT",
        "featuresTitle": "TECHNICAL DETAILS",
        "featureDescription": "",
      },
      {
        "id": 108,
        "group": 1,
        "pattern": "GRABBER GT",
        "featuresTitle": "Performance;",
        "featureDescription": "The Grabber GT has a high degree of rigidity and a well-balanced tread structure. This ensures excellent handling on dry and wet roads.",
      },
      {
        "id": 108,
        "group": 1,
        "pattern": "GRABBER GT",
        "featuresTitle": "Comfort;",
        "featureDescription": "High driving comfort due to reduced noise level",
      },
      {
        "id": 108,
        "group": 1,
        "pattern": "GRABBER GT",
        "featuresTitle": "",
        "featureDescription": "The robust tread minimizes wear. Throughout the service life of the tyre it provides a comfortable ride and noise level is low.",
      },
      {
        "id": 108,
        "group": 1,
        "pattern": "GRABBER GT",
        "featuresTitle": "Performance",
        "featureDescription": "Excellent wet braking performance.",
      },
      {
        "id": 108,
        "group": 1,
        "pattern": "GRABBER GT",
        "featuresTitle": "Visual Alignment Indicator",
        "featureDescription": "VAI signals incorrect alignment.",
      },
      {
        "id": 108,
        "group": 1,
        "pattern": "GRABBER GT",
        "featuresTitle": "",
        "featureDescription": "If the tread wears unevenly over the first 1,000 kilometers, the Visual Alignment indicator technology signals this to the user. This significantly extends service life of the tyre.",
      },
      {
        "id": 108,
        "group": 1,
        "pattern": "GRABBER GT",
        "featuresTitle": "Safety",
        "featureDescription": "RTM- Replacement Tire Monitor for greater safety.",
      },
      {
        "id": 108,
        "group": 1,
        "pattern": "GRABBER GT",
        "featuresTitle": "",
        "featureDescription": "RTM technology tels the driver in good time when a tyre change is due, which increases safety",
      }













      ,
      {
        "id": 108,
        "group": 1,
        "pattern": "ATREZZO ECO",
        "featuresTitle": "",
        "featureDescription": "Specially developed HP fuel-saving tyre for smaller city-cars and compact vehicles with optimised pattern design",
      },
      {
        "id": 108,
        "group": 1,
        "pattern": "ATREZZO ECO",
        "featuresTitle": "",
        "featureDescription": "Optimal safety level even under wet road conditions",
      },
      {
        "id": 108,
        "group": 1,
        "pattern": "ATREZZO ECO",
        "featuresTitle": "",
        "featureDescription": "Low RR-compound for better fuel economy and very low tyre noise",
      },
      {
        "id": 108,
        "group": 1,
        "pattern": "ATREZZO ECO",
        "featuresTitle": "",
        "featureDescription": "High steering response and excellent braking",
      },
      {
        "id": 108,
        "group": 1,
        "pattern": "ATREZZO ECO",
        "featuresTitle": "FEATURES",
        "featureDescription": "",
      },
      {
        "id": 108,
        "group": 1,
        "pattern": "ATREZZO ECO",
        "featuresTitle": "GRIP/PERFORMANCE",
        "featureDescription": "Three wide longitudinal grooves and small lateral grooves located on the sidewall blocks effectively enhance wet grip and resist hydroplaning at high speeds",
      },
      {
        "id": 108,
        "group": 1,
        "pattern": "ATREZZO ECO",
        "featuresTitle": "TREAD DESIGN",
        "featureDescription": "Two centre ribs and reinforcing grooves help improve tyre rigidity; offer excellent handling when driving straight and can effectively reduce rolling resistance and improve fuel efficiency",
      },
      {
        "id": 108,
        "group": 1,
        "pattern": "ATREZZO ECO",
        "featuresTitle": "INTERNAL STRUCTURE:",
        "featureDescription": "Adjusted the internal structure of the tyre to optimise the distribution of contact stress which improves comfort and lowers rolling resistance",
      },



      {
        "id": 108,
        "group": 1,
        "pattern": "ATREZZO ELITE",
        "featuresTitle": "WIDE GROOVES",
        "featureDescription": "Four straight wide grooves connected by transverse sipes increase wet grip by effectively draining and removing water.",
      },
      {
        "id": 108,
        "group": 1,
        "pattern": "ATREZZO ELITE",
        "featuresTitle": "TREAD DESIGN",
        "featureDescription": "Simple staggered layer groove design makes the pattern more dynamic. Outer groove not only makes the outer block more robust, but also improves the handling performance",
      },
      {
        "id": 108,
        "group": 1,
        "pattern": "ATREZZO ELITE",
        "featuresTitle": "ASYMMETRIC TREAD",
        "featureDescription": "Inner tread elements help provide efficient drainage, and the outer tread elements offer exceptional handling to obtain optimal driving performance",
      },
      {
        "id": 108,
        "group": 1,
        "pattern": "ATREZZO ELITE",
        "featuresTitle": "",
        "featureDescription": "RTM technology tels the driver in good time when a tyre change is due, which increases safety",
      },



      {
        "id": 108,
        "group": 1,
        "pattern": "ATREZZO ZSR",
        "featuresTitle": "",
        "featureDescription": "The new generation ATREZZO ZSR is engineered to deliver precise wet and dry handling performance. With an asymmetrical tread design and enhanced tread rubber formula, Atrezzo ZSR rises to the challenge and provides exceptional performance on the street and on the highway.",
      },
      {
        "id": 108,
        "group": 1,
        "pattern": "ATREZZO ZSR",
        "featuresTitle": "FEATURES",
        "featureDescription": "Asymmetrical tread design for uncompromising performance.",
      },
      {
        "id": 108,
        "group": 1,
        "pattern": "ATREZZO ZSR",
        "featuresTitle": "",
        "featureDescription": "Wide shoulder blocks and high angle sipes improve high speed performance",
      }









      ,
      {
        "id": 108,
        "group": 1,
        "pattern": "ATREZZO ZSR",
        "featuresTitle": "",
        "featureDescription": "Variable pitch tread design provides a smooth, quiet ride.",
      },
      {
        "id": 108,
        "group": 1,
        "pattern": "ATREZZO ZSR",
        "featuresTitle": "",
        "featureDescription": "Advanced tread compound delivers superior cornering and exceptional handling.",
      },
      {
        "id": 108,
        "group": 1,
        "pattern": "ATREZZO ZSR",
        "featuresTitle": "",
        "featureDescription": "Deep, circumferential grooves and hundreds of biting edges deliver excellent wet and dry traction.",
      },
      {
        "id": 108,
        "group": 1,
        "pattern": "ATREZZO ZSR",
        "featuresTitle": "EXCEPTIONAL HANDLING",
        "featureDescription": "Wide shoulder tread block with high angle sipes for high-speed cornering performance",
      },
      {
        "id": 108,
        "group": 1,
        "pattern": "ATREZZO ZSR",
        "featuresTitle": "SOLID CENTER RIB",
        "featureDescription": "The tread design features a solid center rib for superior stability and road feel.",
      },
      {
        "id": 108,
        "group": 1,
        "pattern": "ATREZZO ZSR",
        "featuresTitle": "SUPERIOR TRACTION",
        "featureDescription": "Extra-wide grooves for improved wet performance and reduce hydroplaning.",
      },







      {
        "id": 108,
        "group": 1,
        "pattern": "ATREZZO Z4+AS",
        "featuresTitle": "",
        "featureDescription": "The Z4+AS is an ultra-high performance tyre designed for uncompromising performance under all weather conditions. Engineered for high-speed performance, cornering, and braking, the Z4+AS lets you get more out of your car.",
      },
      {
        "id": 108,
        "group": 1,
        "pattern": "ATREZZO Z4+AS",
        "featuresTitle": "",
        "featureDescription": "Optimised to deliver a balance between ultra-high performance needs and comfort of everyday driving in all weather conditions",
      },
      {
        "id": 108,
        "group": 1,
        "pattern": "ATREZZO Z4+AS",
        "featuresTitle": "",
        "featureDescription": "Special silica blends maximize grip and handling stability in dry while maintaining outstanding wear characteristics.",
      },

      {
        "id": 108,
        "group": 1,
        "pattern": "ATREZZO Z4+AS",
        "featuresTitle": "FEATURES",
        "featureDescription": "",
      },
      {
        "id": 108,
        "group": 1,
        "pattern": "ATREZZO Z4+AS",
        "featuresTitle": "GROOVED TREAD BLOCK WALLS:",
        "featureDescription": "Reinforces block stiffness, promoting even load distribution, improved handling and wear characteristics. Designed to reduce pipe resonance for a more comfortable and quiet ride.",
      },
      {
        "id": 108,
        "group": 1,
        "pattern": "ATREZZO Z4+AS",
        "featuresTitle": "TAPERED TREAD EDGES",
        "featureDescription": "Promotes uniform contact pressure for improved stability.",
      },
      {
        "id": 108,
        "group": 1,
        "pattern": "ATREZZO Z4+AS",
        "featuresTitle": "HIGH ANGLE V-SHAPED TREAD GROOVES:",
        "featureDescription": "Aggressive high angle grooves enhance water evacuation to improve wet handling and hydroplane resistance.",
      },



      {
        "id": 108,
        "group": 1,
        "pattern": "COMMERCIO VX1",
        "featuresTitle": "",
        "featureDescription": "The COMMERCIO VX1 is a light truck tire engineered for commercial delivery and demanding regional applications",
      },
      {
        "id": 108,
        "group": 1,
        "pattern": "COMMERCIO VX1",
        "featuresTitle": "",
        "featureDescription": "Featuring an enhanced compound to resist tire damage as well as a reinforced casing to improve load capacity",
      },
      {
        "id": 108,
        "group": 1,
        "pattern": "COMMERCIO VX1",
        "featuresTitle": "",
        "featureDescription": "The Commercio VX1 delivers exceptional mileage and tread-life.",
      },
      {
        "id": 108,
        "group": 1,
        "pattern": "COMMERCIO VX1",
        "featuresTitle": "",
        "featureDescription": "New profile design with a significantly improved carrying capacity.",
      },
      {
        "id": 108,
        "group": 1,
        "pattern": "COMMERCIO VX1",
        "featuresTitle": "",
        "featureDescription": "Strengthened tread construction, abrasion resistance and puncture resistance.",
      },
      {
        "id": 108,
        "group": 1,
        "pattern": "COMMERCIO VX1",
        "featuresTitle": "FEATURES",
        "featureDescription": "",
      },
      {
        "id": 108,
        "group": 1,
        "pattern": "COMMERCIO VX1",
        "featuresTitle": "MAIN GROOVE DESIGN",
        "featureDescription": "Three main grooves are designed to effectively drain water and offer greater high speed stability on wet and dry roads; improved traction and hydroplaning resistance.",
      },
      {
        "id": 108,
        "group": 1,
        "pattern": "COMMERCIO VX1",
        "featuresTitle": "NEW SIPE DESIGN",
        "featureDescription": "New sipe design on the center blocks and shoulder improve handling and grip, dissipate heat, improve traction, and offer greater driving comfort.",
      },
      {
        "id": 108,
        "group": 1,
        "pattern": "COMMERCIO VX1",
        "featuresTitle": "VARIABLE PITCH DESIGN",
        "featureDescription": "The tread is constructed with a variable pitch design which significantly reduces noise emissions for a more comfortable driving experience.",
      }
      
      
      
      
      
      
      
      ,
      {
        "id": 108,
        "group": 1,
        "pattern": "TERRAMAX CVR",
        "featuresTitle": "",
        "featureDescription": "The TERRAMAX CVR is an all-season tire specifically engineered for SUV and crossovers. The CVR delivers exceptional handling and stability for today's crossover vehicles without compromising ride comfort",
      },
      {
        "id": 108,
        "group": 1,
        "pattern": "TERRAMAX CVR",
        "featuresTitle": "",
        "featureDescription": "Smooth and quiet ride for a more comfortable driving experience",
      },
      {
        "id": 108,
        "group": 1,
        "pattern": "TERRAMAX CVR",
        "featuresTitle": "",
        "featureDescription": "Top all-around performance on wet and dry roads",
      },
      {
        "id": 108,
        "group": 1,
        "pattern": "TERRAMAX CVR",
        "featuresTitle": "",
        "featureDescription": "Excellent handling and a stable ride, especially at high speeds.",
      },
      {
        "id": 108,
        "group": 1,
        "pattern": "TERRAMAX CVR",
        "featuresTitle": "",
        "featureDescription": "Durable and long lasting design.",
      },
      {
        "id": 108,
        "group": 1,
        "pattern": "TERRAMAX CVR",
        "featuresTitle": "",
        "featureDescription": "Suitable for off-road usage.",
      },
      {
        "id": 108,
        "group": 1,
        "pattern": "TERRAMAX CVR",
        "featuresTitle": "",
        "featureDescription": "H, V, W rated construction.",
      },
      {
        "id": 108,
        "group": 1,
        "pattern": "TERRAMAX CVR",
        "featuresTitle": "FEATURES",
        "featureDescription": "",
      },
      {
        "id": 108,
        "group": 1,
        "pattern": "TERRAMAX CVR",
        "featuresTitle": "GROOVE DESIGN",
        "featureDescription": "Four main grooves and small gradually winding lateral grooves reduce rolling resistance and effectively drain water for improved hydroplaning resistance.",
      },
      {
        "id": 108,
        "group": 1,
        "pattern": "TERRAMAX CVR",
        "featuresTitle": "LARGE SHOULDER BLOCKS",
        "featureDescription": "Large shoulder blocks and center ribs provide responsiveness and high speed stability",
      },
      {
        "id": 108,
        "group": 1,
        "pattern": "TERRAMAX CVR",
        "featuresTitle": "TREAD DESIGN",
        "featureDescription": "Tread design offers greater driving comfort and reduces noise emissions",
      },










      {
        "id": 108,
        "group": 1,
        "pattern": "GRABBER AT2",
        "featuresTitle": "",
        "featureDescription": "This tough, all-terrain tire is designed with an aggressive, self-cleaning tread pattern that provides off-road traction, durability and impressive paved road performance.",
      },
      {
        "id": 108,
        "group": 1,
        "pattern": "GRABBER AT2",
        "featuresTitle": "5-Row Tread Pattern with Multiple Traction Edges:",
        "featureDescription": "",
      },
      {
        "id": 108,
        "group": 1,
        "pattern": "GRABBER AT2",
        "featuresTitle": "",
        "featureDescription": "Innovative tread design promotes uncompromising on and off-road traction. ",
      },
      {
        "id": 108,
        "group": 1,
        "pattern": "GRABBER AT2",
        "featuresTitle": "Double V-Shaped Tread Pattern: ",
        "featureDescription": "",
      },
      {
        "id": 108,
        "group": 1,
        "pattern": "GRABBER AT2",
        "featuresTitle": "",
        "featureDescription": "Designed to increase tread life and off-road durability. ",
      },
      {
        "id": 108,
        "group": 1,
        "pattern": "GRABBER AT2",
        "featuresTitle": "Highly-Engineered Acoustic Tread Pattern:",
        "featureDescription": "",
      },
      {
        "id": 108,
        "group": 1,
        "pattern": "GRABBER AT2",
        "featuresTitle": "",
        "featureDescription": "Allows the aggressive tread pattern to provide a quiet, comfortable ride during highway driving. ",
      },
      {
        "id": 108,
        "group": 1,
        "pattern": "GRABBER AT2",
        "featuresTitle": "Snowflake Approved* and Studdable Design:",
        "featureDescription": "",
      },
      {
        "id": 108,
        "group": 1,
        "pattern": "GRABBER AT2",
        "featuresTitle": "",
        "featureDescription": "Meets the severe snow service requirements of the RMA and RAC",
      },

    ]
})

export const getters = {
    selectfeature (state){
        return state.selectfeature
    }
}

export const mutations = {
    SET_SELECT_PATTERN_FEATURE (state, pattern) {
        for (var item, i = 0; item = state.features[i++];) {
            if (pattern == item.pattern) {
                state.selectfeature.push(item);
            }
        }
    },
    SET_CLEAR_FEATURE_SELECTION (state, data) {
        state.selectfeature = data
    },
}

export const actions = {
    async setSelectPattaern ({ commit }, pattern) {
        commit('SET_SELECT_PATTERN_FEATURE', pattern)
    },
    clearSelectFeaturs ({ commit }) {
        commit('SET_CLEAR_FEATURE_SELECTION', [])
    },
}