export const state = () => ({
    selectfeature:[],
    features: [{
        "id": 2,
        "group": 1,
        "pattern": "K114",
        "featuresTitle": "RIB SHOULDER BLOCK:",
        "featureDescription": "It delivers excellent performance through block stiffness optimization.",
      },
      {
        "id": 3,
        "group": 1,
        "pattern": "K114",
        "featuresTitle": "OPTIMAL 4-CHANNEL GROOVE:",
        "featureDescription": "It adopts the optimal 4-channel groove by SCCT and multiple tread radius technology for pattern stiffness optimization.",
      },
      {
        "id": 4,
        "group": 1,
        "pattern": "K114",
        "featuresTitle": "SHOULDER BLOCK",
        "featureDescription": "It delivers excellent dry handling performance through the shoulder block width increase and contact space increase.",
      },
      {
        "id": 5,
        "group": 1,
        "pattern": "K114",
        "featuresTitle": "Tire Structure",
        "featureDescription": "It adopts the optimal tread compound (natural glass) that meets both RR and noise/comfort requirements. It adopts ventless mold (MSV) technology to improve appearance/noise performance.",
      },
      {
        "id": 6,
        "group": 1,
        "pattern": "K114",
        "featuresTitle": "TWOFOLD JOINTLESS FULL COVER",
        "featureDescription": "It improves durability and breaking performance. It improves steering stability by maintaining the equal foot shape tread part.",
      },
      {
        "id": 7,
        "group": 1,
        "pattern": "K114",
        "featuresTitle": "WEIGHT DOWN/SOLID BELT CORD",
        "featureDescription": "It improves fuel efficiency and steering stability. It applies the rim protect bar for aggressive appearance and rim protection.",
      },
      {
        "id": 8,
        "group": 1,
        "pattern": "K114",
        "featuresTitle": "HIGH HARDNESS BEAD FILLER",
        "featureDescription": "It improves durability and steering stability.",
      },
      {
        "id": 9,
        "group": 1,
        "pattern": "RA23",
        "featuresTitle": "UNIQUE DESIGN",
        "featureDescription": "Improved off-road and snow performance.",
      },
      {
        "id": 10,
        "group": 1,
        "pattern": "RA23",
        "featuresTitle": "EMBOSSED STYLE",
        "featureDescription": "Improved off-road performance with an aggressive SUV appearance.",
      },
      {
        "id": 11,
        "group": 1,
        "pattern": "RA23",
        "featuresTitle": "2-STEP GRADUATED GROOVE",
        "featureDescription": "Discharges water rapidly from the tread surface to prevent hydroplaning.",
      },
      {
        "id": 12,
        "group": 1,
        "pattern": "RA23",
        "featuresTitle": "FOUR STRAIGHT CHANNEL GROOVES",
        "featureDescription": "Resists hydroplaning, providing increased aquaplaning performance.",
      },
      {
        "id": 13,
        "group": 1,
        "pattern": "RA23",
        "featuresTitle": "SEMI-GROOVE",
        "featureDescription": "Uniform contact area provides improved on wet and snowy surfaces.",
      },
      {
        "id": 14,
        "group": 1,
        "pattern": "RA23",
        "featuresTitle": "TIE BAR",
        "featureDescription": "A greater circumferential and lateral stiffness enables improved dry braking, pass-by noise and prevents uneven wear.",
      },
      {
        "id": 15,
        "group": 1,
        "pattern": "RA23",
        "featuresTitle": "CENTRE RIB",
        "featureDescription": "Improved dry braking, handling and steering response.",
      },
      {
        "id": 16,
        "group": 1,
        "pattern": "RA23",
        "featuresTitle": "NOISE-REDUCTION KERF",
        "featureDescription": "Prevents a harmonic tread pattern sound.",
      },
      {
        "id": 17,
        "group": 1,
        "pattern": "RA23",
        "featuresTitle": "Rolling resistance",
        "featureDescription": "Jointless cap ply around the circumference of the tyre over the steel belts assures enhanced belt endurance plus improved uniformity for comfort and high-speed stability",
      },
      {
        "id": 18,
        "group": 1,
        "pattern": "RA23",
        "featuresTitle": "WIDE, HIGH-TENSILE STEEL BELTS:",
        "featureDescription": "Enhance tread strength for steering response and wear life.",
      },
      {
        "id": 19,
        "group": 1,
        "pattern": "K715",
        "featuresTitle": "TIE BAR FOR SHOULDER AREA:",
        "featureDescription": "Shoulder area is bolstered by a tie bar, improving rigidity and therefore handling.",
      },
      {
        "id": 20,
        "group": 1,
        "pattern": "K715",
        "featuresTitle": "SHOULDER KERF REDUCES UNEVEN WEAR",
        "featureDescription": "Uneven abrasion which could be generated while cornering is diminished by the insertion of a kerf in the shoulder area",
      },
      {
        "id": 21,
        "group": 1,
        "pattern": "K715",
        "featuresTitle": "OPTIMISED PITCH SEQUENCE",
        "featureDescription": "A quieter ride and better handling are ensured by optimising the pitch sequence",
      },
      {
        "id": 22,
        "group": 1,
        "pattern": "K715",
        "featuresTitle": "REVISED GROOVE POSITIONING",
        "featureDescription": "Strategic positioning and width adjustment of grooves ensure more safety in wet conditions.",
      },
      {
        "id": 23,
        "group": 1,
        "pattern": "K715",
        "featuresTitle": "JOINTLESS CAP PLY",
        "featureDescription": "Improving uniformity for a smooth ride and higher durability.",
      },
      {
        "id": 24,
        "group": 1,
        "pattern": "K715",
        "featuresTitle": "WIDE, HIGH-TENSILE STEEL BELTS",
        "featureDescription": "1Enhancing tread strength for a more direct steering response and less wear.",
      },
      {
        "id": 25,
        "group": 1,
        "pattern": "K715",
        "featuresTitle": "JOINTLESS BEAD WIRE & HIGH TENSILE MODULUS BEAD FILLER",
        "featureDescription": "Improving high speed stability and ride comfort. Maximising steering response and durability.",
      },
      {
        "id": 26,
        "group": 1,
        "pattern": "K110",
        "featuresTitle": "3D EFFECT ON BLOCK EDGE",
        "featureDescription": "Diverse angles of the block edge result in a sophisticated design with a three-dimensional effect. Ground contact pressure is evenly distributed for optimal handling and braking",
      },
      {
        "id": 27,
        "group": 1,
        "pattern": "K110",
        "featuresTitle": "SOLID CENTER RIB BLOCK:",
        "featureDescription": "The solid rib block in the center enhances braking performance. It also ensures optimal ground contact pressure and control response at high speeds for excellent handling",
      },
      {
        "id": 28,
        "group": 1,
        "pattern": "K110",
        "featuresTitle": "EFFICIENT WATER DRAINAGE",
        "featureDescription": "Wide linear grooves and an aggressive Y-shape pattern design effectively channels water away from the tire.",
      },
      {
        "id": 29,
        "group": 1,
        "pattern": "K110",
        "featuresTitle": "HIGH-DENSITY NYLON FULL COVER",
        "featureDescription": "Optimized structure featuring a high-density nylon belt leads to even distribution of ground contact pressure during cornering.",
      },
      {
        "id": 30,
        "group": 1,
        "pattern": "RH07",
        "featuresTitle": "6 CIRCUMFERENTIAL GROOVES",
        "featureDescription": "Cools the tire, improves steerability and allows water to escape the footprint",
      },
      {
        "id": 31,
        "group": 1,
        "pattern": "RH07",
        "featuresTitle": "SOLID CENTERLINE",
        "featureDescription": "Improves driving feel and stability.",
      },
      {
        "id": 32,
        "group": 1,
        "pattern": "RH07",
        "featuresTitle": "OPEN SHOULDER DESIGN",
        "featureDescription": "Provides “see-thru” evacuation of water and slush.",
      },
      {
        "id": 33,
        "group": 1,
        "pattern": "RH07",
        "featuresTitle": "HIGH DENSITY SIPING",
        "featureDescription": "Gives the Ventus AS hundreds of biting edges for noise performance",
      },
      {
        "id": 34,
        "group": 1,
        "pattern": "RH07",
        "featuresTitle": "STEPPED GROOVE WALLS",
        "featureDescription": "Provide extra edges for steering traction",
      },
      {
        "id": 35,
        "group": 1,
        "pattern": "RH07",
        "featuresTitle": "Tire Structure",
        "featureDescription": "Rim protect bar protects the rim from scuffing while preventing the sidewall from “rolling over” the rim flange.Sidewall shape optimized to bend gently-reducing stresses and improving ride comfort.",
      },
      {
        "id": 36,
        "group": 1,
        "pattern": "RH07",
        "featuresTitle": "",
        "featureDescription": "Sidewall compound specially formulated to resist ozone, aging, cracking and abrasion.",
      },
      {
        "id": 37,
        "group": 1,
        "pattern": "RH07",
        "featuresTitle": "",
        "featureDescription": "Nylon belt overlay provides strength to the tread area and restricts belt motion-the key to high performance handling.",
      },
      {
        "id": 38,
        "group": 1,
        "pattern": "RH07",
        "featuresTitle": "",
        "featureDescription": "Two extra-wide high tensile steel belts give the tire crisp handling and flex to absorb road shocks.",
      },
      {
        "id": 39,
        "group": 1,
        "pattern": "RF10",
        "featuresTitle": "RUGGED PUNCTURE RESISTANCE",
        "featureDescription": "Wraparound tread gives tire a rugged look and guards against cuts, bruises and impact breaks. Affords outstanding traction, especially in muddy or snowy conditions.",
      },
      {
        "id": 40,
        "group": 1,
        "pattern": "RF10",
        "featuresTitle": "TREAD PATTERN",
        "featureDescription": "The sharp edge patterned after tiger's teeth creates an aggressive, bold look balanced block design.",
      },
      {
        "id": 41,
        "group": 1,
        "pattern": "RF10",
        "featuresTitle": "WAVE KERF",
        "featureDescription": "Deep two step sipes extend tread life and increases performance on wet road.",
      },
      {
        "id": 42,
        "group": 1,
        "pattern": "RF10",
        "featuresTitle": "DEEP DEPTH TIERED SIDE GROOVE",
        "featureDescription": "Precise & Stable Cornering The tiered groove is applied, which makes a moving angle of the tread block smaller compared to the conventional non-tiered groove when cornering, to secure safer cornering running performance.",
      },
      {
        "id": 43,
        "group": 1,
        "pattern": "RF10",
        "featuresTitle": "STONE EJECTOR",
        "featureDescription": "Stone ejectors in the center and shoulder grooves help prevent tire damage from stones or external impacts. Also enhances handling confidence",
      },
      {
        "id": 44,
        "group": 1,
        "pattern": "RF10",
        "featuresTitle": "SCALLOP GROOVES",
        "featureDescription": "The “Scallop grooves” between the tread blocks increase the tire’s ‘biting’ edges to enhance traction off-road.",
      },
      {
        "id": 45,
        "group": 1,
        "pattern": "RF10",
        "featuresTitle": "ANGLED SIDE GROOVE",
        "featureDescription": "Enhances wet traction has self-cleaning capabilities.",
      },
      {
        "id": 46,
        "group": 1,
        "pattern": "RF10",
        "featuresTitle": "ZIG ZAG BLOCK EDGE",
        "featureDescription": "Provides superb grip in wet, icy and dry conditions.",
      },
      {
        "id": 47,
        "group": 1,
        "pattern": "RF10",
        "featuresTitle": "WIDE TREAD",
        "featureDescription": "The footprint has been enlarged (7-8% increase more than comparable products) to resist uneven wear while providing the best grip and acceleration under all road conditions.",
      },
      {
        "id": 48,
        "group": 1,
        "pattern": "RF10",
        "featuresTitle": "RIM FLANGE PROTECTOR",
        "featureDescription": "Guards expensive wheels from accidental curb damage.",
      },
      {
        "id": 49,
        "group": 1,
        "pattern": "RF10",
        "featuresTitle": "REINFORCED UNDER-TREAD GAUGE",
        "featureDescription": "Helps to prevent internal damage from impacts sustained when off the road.",
      },
      {
        "id": 50,
        "group": 1,
        "pattern": "RF10",
        "featuresTitle": "THICK SIDEWALL RUBBER GAUGE",
        "featureDescription": "Helps to minimize damage from off-road impact",
      },
      {
        "id": 51,
        "group": 1,
        "pattern": "RF10",
        "featuresTitle": "REINFORCED CARCASS",
        "featureDescription": "Improved or Improves hill climbing and steering stability both on and off the road.",
      },
      {
        "id": 52,
        "group": 1,
        "pattern": "RF10",
        "featuresTitle": "JOINTLESS BEAD WIRE",
        "featureDescription": "Prevents bead separation when driving off-road on low air pressure.",
      },
      {
        "id": 53,
        "group": 1,
        "pattern": "K115",
        "featuresTitle": "BIONIC PATTERN DESIGN FOR INCREASED GRIP PERFORMANCE:",
        "featureDescription": "Jaguar’s tooth shape design insures to secure optimum grip. This feature allows for better handling in all driving conditions.",
      },
      {
        "id": 54,
        "group": 1,
        "pattern": "K115",
        "featuresTitle": "ENHANCED WET PERFORMANCE TECHNOLOGY",
        "featureDescription": "Features a triple-radius profile that helps maintain maximum grip in wet conditions",
      },
      {
        "id": 55,
        "group": 1,
        "pattern": "K424",
        "featuresTitle": "",
        "featureDescription": "It’s a specially customized tire for the harsh climatic conditions of the Middle East Region",
      },
      {
        "id": 56,
        "group": 1,
        "pattern": "K424",
        "featuresTitle": "",
        "featureDescription": "It applies innovative reduction of rolling resistance and cutting edge technology compared with the existing and competing products, which makes you remember its strong impression.",
      },
      {
        "id": 57,
        "group": 1,
        "pattern": "H437",
        "featuresTitle": "A SPEED REVOLUTION",
        "featureDescription": "You can enjoy a ‘stable high-speed ride on a wet conditions’ with the innovative technology exclusive to Hankook Tire.",
      },
      {
        "id": 58,
        "group": 1,
        "pattern": "H437",
        "featuresTitle": "",
        "featureDescription": "More Performance! The best ‘stability of steering’ and ‘brake performance’ that you can find. Realize the dream of driving.",
      },
      {
        "id": 59,
        "group": 1,
        "pattern": "K117",
        "featuresTitle": "AQUA DRIVING CONTROL",
        "featureDescription": "Provides superior wet performance through rapid drainage",
      },
      {
        "id": 60,
        "group": 1,
        "pattern": "K117",
        "featuresTitle": "TRIPLE DRIVELINE",
        "featureDescription": "As wear progresses down to TWI (tread wear indicator), there is no loss in performance.",
      },
      {
        "id": 61,
        "group": 1,
        "pattern": "K117",
        "featuresTitle": "COOLING SYSTEM",
        "featureDescription": "Speeds up water drainage and improves heat radiation at high speed.",
      },
      {
        "id": 62,
        "group": 1,
        "pattern": "K117",
        "featuresTitle": "INTERCOOLER",
        "featureDescription": "Controls excessive heat buildup.",
      },
      {
        "id": 63,
        "group": 1,
        "pattern": "K117",
        "featuresTitle": "ALIGNMENT INDICATOR",
        "featureDescription": "Drivers can check status of the vehicle alignment themselves through in or out wear check.",
      },
      {
        "id": 64,
        "group": 1,
        "pattern": "K117",
        "featuresTitle": "HIGH GRIP SILICA COMPOUND",
        "featureDescription": "Improved dry or wet traction and lower rolling resistance.",
      },
      {
        "id": 65,
        "group": 1,
        "pattern": "K117",
        "featuresTitle": "WIDE STEEL BELT LAYER",
        "featureDescription": "Better dry or wet handling",
      },
      {
        "id": 66,
        "group": 1,
        "pattern": "K117",
        "featuresTitle": "EQUILIBRIUM RAYON CARCASS LINE",
        "featureDescription": "Enhance sidewall stiffness and durability.",
      },
      {
        "id": 67,
        "group": 1,
        "pattern": "K117",
        "featuresTitle": "HIGH STIFFNESS BEAD FILLER",
        "featureDescription": "Better handling and steering response.",
      },
      {
        "id": 68,
        "group": 1,
        "pattern": "K117",
        "featuresTitle": "STRONG SINGLE BEAD WIRE",
        "featureDescription": "Improved uniformity and tire fitting.",
      },
      {
        "id": 69,
        "group": 1,
        "pattern": "RA33",
        "featuresTitle": "STRAIGHT 4-CHANNEL WATERWAY",
        "featureDescription": "Resists Hydroplaning & Aquaplaning Performance Up",
      },
      {
        "id": 70,
        "group": 1,
        "pattern": "RA33",
        "featuresTitle": "HIGH STIFFNESS CENTER RIB",
        "featureDescription": "Stiff Center Tread Blocks provide precise steering.",
      },
      {
        "id": 71,
        "group": 1,
        "pattern": "RA33",
        "featuresTitle": "SILENCER SIPES",
        "featureDescription": "Prevents harmonic tread pattern sound",
      },
      {
        "id": 72,
        "group": 1,
        "pattern": "RA33",
        "featuresTitle": "AQUA SLANT SIPES & GROOVE",
        "featureDescription": "Radial direction sipes provide improved handling in wet and dry conditions by locking together for greater rigidity. Lateral grooves provide resistance to hydroplaning.",
      },
      {
        "id": 73,
        "group": 1,
        "pattern": "RA33",
        "featuresTitle": "HIGH LOADING SILICA COMPOUND",
        "featureDescription": "Dry/wet traction is improved and rolling resistance is lowered",
      },
      {
        "id": 74,
        "group": 1,
        "pattern": "RA33",
        "featuresTitle": "WIDE 2 STEEL BELT LAYER",
        "featureDescription": "Better Dry/Wet Handling",
      },
      {
        "id": 75,
        "group": 1,
        "pattern": "RA33",
        "featuresTitle": "HIGH DENSITY POLYESTER CARCASS",
        "featureDescription": "Better steering & handling response",
      },
      {
        "id": 76,
        "group": 1,
        "pattern": "RA33",
        "featuresTitle": "STRONG SINGLE STRAND BEAD WIRE:",
        "featureDescription": "Better steering and handling response",
      },
      {
        "id": 77,
        "group": 1,
        "pattern": "K120",
        "featuresTitle": "ALIGNMENT INDICATOR",
        "featureDescription": "Drivers can check the status of the vehicle alignment themselves through in or out wear check.",
      },
      {
        "id": 78,
        "group": 1,
        "pattern": "K120",
        "featuresTitle": "AQUA JET",
        "featureDescription": "Aqua jet is the catalyst to channel water effectively out of the center to the main groove wall.",
      },
      {
        "id": 79,
        "group": 1,
        "pattern": "K120",
        "featuresTitle": "COOLING SYSTEM",
        "featureDescription": "Speeds up water drainage and improves heat radiation at high speed.",
      },
      {
        "id": 80,
        "group": 1,
        "pattern": "K120",
        "featuresTitle": "STEALTH TECHNOLOGY",
        "featureDescription": "Unique wing tip design reduces noise using ‘Stealth technology’. Slanted edges support the blocks during handling where sounds or trembling hits. This slanted surface reduces impact.",
      },
      {
        "id": 81,
        "group": 1,
        "pattern": "K120",
        "featuresTitle": "ADVANCED NOISE",
        "featureDescription": "Increased pitch numbers reduced noise.",
      },
      {
        "id": 82,
        "group": 1,
        "pattern": "K120",
        "featuresTitle": "COMPOUND TECHNOLOGY",
        "featureDescription": "Application of new styrene polymer featuring a functional group improves the chemical combination.",
      },
      {
        "id": 83,
        "group": 1,
        "pattern": "K120",
        "featuresTitle": "HIGH GRIP SILICA COMPOUND",
        "featureDescription": "Improved dry and wet traction and lower rolling resistance.",
      },
      {
        "id": 84,
        "group": 1,
        "pattern": "K120",
        "featuresTitle": "WIDE STEEL BELT LAYER",
        "featureDescription": "Better dry or wet handling.",
      },
      {
        "id": 85,
        "group": 1,
        "pattern": "K120",
        "featuresTitle": "HIGH DENSITY POLYESTER CARCASS",
        "featureDescription": "Enhanced sidewall stiffness and durability.",
      },
      {
        "id": 86,
        "group": 1,
        "pattern": "K120",
        "featuresTitle": "HIGH STIFFNESS BEAD FILLER",
        "featureDescription": "Better steering and handling response.",
      },
      {
        "id": 87,
        "group": 1,
        "pattern": "K120",
        "featuresTitle": "STRONG SINGLE BEAD WIRE",
        "featureDescription": "Improved uniformity and tire fitting.",
      },
      {
        "id": 88,
        "group": 1,
        "pattern": "RT03",
        "featuresTitle": "SIDE PROTECTION BLOCK",
        "featureDescription": "A side protection block from the tread pattern to the center of the sidewall has an appealing rugged look and shields against the shock of protruding objects. This also improves traction in soft dirt and protects pothole damage.",
      },
      {
        "id": 89,
        "group": 1,
        "pattern": "RT03",
        "featuresTitle": "ZIG ZAG SHOULDER LUGS",
        "featureDescription": "Zigzag shoulder pattern delivers greater off-road traction. (dry: 100km/h, wet: 80km/h).",
      },
      {
        "id": 90,
        "group": 1,
        "pattern": "RT03",
        "featuresTitle": "UNDER-GROOVE PROTECTOR",
        "featureDescription": "The tire shoulders are most vulnerable to objects protruding from off-road surfaces. Hankook Tire has added a unique under-groove protector to prevent impact damage and soften external shock for greater driving safety.",
      },







      {
        "id": 90,
        "group": 1,
        "pattern": "K425",
        "featuresTitle": "K425 (KINERGY ECO)",
        "featureDescription": "",
      },
      {
        "id": 90,
        "group": 1,
        "pattern": "K425",
        "featuresTitle": "Innovative tyre technology for eco-friendly and comfortable driving.",
        "featureDescription": "",
      },
      {
        "id": 90,
        "group": 1,
        "pattern": "K425",
        "featuresTitle": "",
        "featureDescription": "With the technology of nano-scale silica particles, the Kinergy Eco provides superb fuel efficiency and excellent wet braking performance.",
      },
      {
        "id": 90,
        "group": 1,
        "pattern": "K425",
        "featuresTitle": "FEATURES",
        "featureDescription": "",
      },
      {
        "id": 90,
        "group": 1,
        "pattern": "K425",
        "featuresTitle": "TYRE PATTERN",
        "featureDescription": "",
      },
      {
        "id": 90,
        "group": 1,
        "pattern": "K425",
        "featuresTitle": "Tread design",
        "featureDescription": "",
      },
      {
        "id": 90,
        "group": 1,
        "pattern": "K425",
        "featuresTitle": "",
        "featureDescription": "Optimised pitch sequence - Ensures more quiet ride and better handling.",
      },
      {
        "id": 90,
        "group": 1,
        "pattern": "K425",
        "featuresTitle": "",
        "featureDescription": "Wide straight three channeled groove - Ensured excellent performance in wet driving conditions",
      },
      {
        "id": 90,
        "group": 1,
        "pattern": "K425",
        "featuresTitle": "",
        "featureDescription": "Lateral shoulder grooves - Designed to improve handling Shoulder Rib Block on dry roads and reduce then any decline in performance under rainy conditions and ride.",
      },
      {
        "id": 90,
        "group": 1,
        "pattern": "K425",
        "featuresTitle": "",
        "featureDescription": "Sawtooth type technology - Improves dry handling without sacrificing wet handling ability.",
      },
      {
        "id": 90,
        "group": 1,
        "pattern": "K117A",
        "featuresTitle": "K117A (VENTUS S1EVO2 SUV)",
        "featureDescription": "",
      },
      {
        "id": 90,
        "group": 1,
        "pattern": "K117A",
        "featuresTitle": "",
        "featureDescription": "The best balance between wet & dry performance for premium SUVs.",
      },
      {
        "id": 90,
        "group": 1,
        "pattern": "K117A",
        "featuresTitle": "",
        "featureDescription": "The ventus S1 evo2 is a premium performance tire for SUVs that shortens braking distances in dry and wet conditions, enhances fuel efficiency based on lowest rolling resistance and provides excellent grip and safety.",
      },
      {
        "id": 90,
        "group": 1,
        "pattern": "K117A",
        "featuresTitle": "FEATURES",
        "featureDescription": "",
      },
      {
        "id": 90,
        "group": 1,
        "pattern": "K117A",
        "featuresTitle": "Tire pattern",
        "featureDescription": "",
      },
      {
        "id": 90,
        "group": 1,
        "pattern": "K117A",
        "featuresTitle": "",
        "featureDescription": "Aqua Driving Control: Providing superior wet performance through rapid drainage",
      },
      {
        "id": 90,
        "group": 1,
        "pattern": "K117A",
        "featuresTitle": "",
        "featureDescription": "Triple Driveline: As wear progresses down to TWI (tread wear indicator), there is no loss in performance",
      },
      {
        "id": 90,
        "group": 1,
        "pattern": "K117A",
        "featuresTitle": "",
        "featureDescription": "Cooling System: Speeds up water drainage and improves heat radiation at high speed",
      },
      {
        "id": 90,
        "group": 1,
        "pattern": "K117A",
        "featuresTitle": "",
        "featureDescription": "Intercooler: Controls excessive heat buildup",
      },
      {
        "id": 90,
        "group": 1,
        "pattern": "K117A",
        "featuresTitle": "",
        "featureDescription": "Alignment Indicator: Drivers can check status of the vehicle alignment themselves through IN / OUT wear check",
      },
      {
        "id": 90,
        "group": 1,
        "pattern": "K117A",
        "featuresTitle": "Tire Structure",
        "featureDescription": "",
      },
      {
        "id": 90,
        "group": 1,
        "pattern": "K117A",
        "featuresTitle": "",
        "featureDescription": "High Grip Silica Compound: Improved Dry/Wet Traction & Lower Rolling Resistance",
      },
      {
        "id": 90,
        "group": 1,
        "pattern": "K117A",
        "featuresTitle": "",
        "featureDescription": "Wide Steel Belt Layer: Better Dry/Wet Handling",
      },
      {
        "id": 90,
        "group": 1,
        "pattern": "K117A",
        "featuresTitle": "",
        "featureDescription": "High Density Rayon and Polyester Carcass: Enhanced sidewall stiffness and durability",
      },
      {
        "id": 90,
        "group": 1,
        "pattern": "K117A",
        "featuresTitle": "",
        "featureDescription": "High Stiffness Bead Filler: Better steering and handling response",
      },
      {
        "id": 90,
        "group": 1,
        "pattern": "K117A",
        "featuresTitle": "",
        "featureDescription": "Strong Single Strand Bead Wire: Improved Uniformity & Tire Fitting",
      },

      {
        "id": 90,
        "group": 1,
        "pattern": "RH12",
        "featuresTitle": "RH12 (DYNAPRO HT)",
        "featureDescription": "",
      },
      {
        "id": 90,
        "group": 1,
        "pattern": "RH12",
        "featuresTitle": "Combining all-season functionality with performance for highway driving",
        "featureDescription": "",
      },
      {
        "id": 90,
        "group": 1,
        "pattern": "RH12",
        "featuresTitle": "",
        "featureDescription": "A sport truck and SUV tire that provides a smooth, powerful ride, the Dynapro HT provides greater mileage through specialized treadwear. Excellent snow traction makes driving possible on winter roads while low-rolling resistance offers excellent fuel economy.",
      },
      {
        "id": 90,
        "group": 1,
        "pattern": "RH12",
        "featuresTitle": "FEATURES",
        "featureDescription": "",
      },
      {
        "id": 90,
        "group": 1,
        "pattern": "RH12",
        "featuresTitle": "TYRE PATTERN",
        "featureDescription": "",
      },
      {
        "id": 90,
        "group": 1,
        "pattern": "RH12",
        "featuresTitle": "",
        "featureDescription": "High stiffness center block - Steering response improvement.",
      },
      {
        "id": 90,
        "group": 1,
        "pattern": "RH12",
        "featuresTitle": "",
        "featureDescription": "Snow kerf - Allows for improved all-season performance.",
      },
      {
        "id": 90,
        "group": 1,
        "pattern": "RH12",
        "featuresTitle": "",
        "featureDescription": "Button and semi solid ribs - Button elements sized for good snow and wet traction, yet interlocking geometry maintains rib stiffness for handling.",
      },
      {
        "id": 90,
        "group": 1,
        "pattern": "RH12",
        "featuresTitle": "",
        "featureDescription": "4 straight groove channels - Ideally arranged channels provide sure-footed performance in both wet and dry conditions.",
      },
      {
        "id": 90,
        "group": 1,
        "pattern": "RH12",
        "featuresTitle": "",
        "featureDescription": "Multi-depth lateral lugs - Provide improved performance in wet and snow conditions throughout the whole tread life.",
      },
      {
        "id": 90,
        "group": 1,
        "pattern": "RH12",
        "featuresTitle": "Tyre Structure",
        "featureDescription": "",
      },
      {
        "id": 90,
        "group": 1,
        "pattern": "RH12",
        "featuresTitle": "",
        "featureDescription": "Unique highway all-season purpose optimized cap tread - LPAH(low polycyclic aromatic hydrocarbon) environment-friendly compound. Optimized compound provides long mileage, braking performance and prevents chips, cuts and abrasions.",
      },
      {
        "id": 90,
        "group": 1,
        "pattern": "RH12",
        "featuresTitle": "",
        "featureDescription": "Reinforced under-tread protective layer - Helps prevent internal damage from impacts sustained when driving.",
      },
      {
        "id": 90,
        "group": 1,
        "pattern": "RH12",
        "featuresTitle": "",
        "featureDescription": "High-tensile strength sidewall rubber - Helps to minimize damage from impacts.",
      },
      {
        "id": 90,
        "group": 1,
        "pattern": "RH12",
        "featuresTitle": "",
        "featureDescription": "Nylon joinless reinforced belts - Increases belt durability.",
      },
      {
        "id": 90,
        "group": 1,
        "pattern": "RH12",
        "featuresTitle": "",
        "featureDescription": "High-strength steel belts - Improves steering stability and durability.",
      },
      {
        "id": 90,
        "group": 1,
        "pattern": "RH12",
        "featuresTitle": "",
        "featureDescription": "Reinforced carcass and rubber gauge - Improves hill climbing and steering stability.",
      },
      {
        "id": 90,
        "group": 1,
        "pattern": "RH12",
        "featuresTitle": "",
        "featureDescription": "Jointless bead wire - Helps prevent bead separation.",
      },

      {
        "id": 90,
        "group": 1,
        "pattern": "RH06",
        "featuresTitle": "RH06 (VENTUS ST)",
        "featureDescription": "",
      },
      {
        "id": 90,
        "group": 1,
        "pattern": "RH06",
        "featuresTitle": "",
        "featureDescription": "The Ventus ST is a high performance tyre designed for SUV’s and sport trucks. This tyre provides outstanding wet and dry performance, sturdy handling and improved mileage.",
      },
      {
        "id": 90,
        "group": 1,
        "pattern": "RH06",
        "featuresTitle": "FEATURES",
        "featureDescription": "",
      },
      {
        "id": 90,
        "group": 1,
        "pattern": "RH06",
        "featuresTitle": "TYRE PATTERN",
        "featureDescription": "",
      },
      {
        "id": 90,
        "group": 1,
        "pattern": "RH06",
        "featuresTitle": "",
        "featureDescription": "Tread Design - V-shaped pattern stands out as the best handling design for both wet and dry conditions.",
      },
      {
        "id": 90,
        "group": 1,
        "pattern": "RH06",
        "featuresTitle": "",
        "featureDescription": "Wear life - The combination of computerised ply line development and footprint shape optimisation yields tread wear results that are unusual for a high performance tyre.",
      },
      {
        "id": 90,
        "group": 1,
        "pattern": "RH06",
        "featuresTitle": "",
        "featureDescription": "Noise - New DDPT (dual depth pitch theory) technology has developed a multiple sub pitch concept which is applied to minimise pattern noise",
      },
      {
        "id": 90,
        "group": 1,
        "pattern": "RH06",
        "featuresTitle": "Tyre Structure",
        "featureDescription": "",
      },
      {
        "id": 90,
        "group": 1,
        "pattern": "RH06",
        "featuresTitle": "",
        "featureDescription": "Jointless bead wire - Strengthens stable performance to provide a comfortable ride.",
      },
      {
        "id": 90,
        "group": 1,
        "pattern": "RH06",
        "featuresTitle": "",
        "featureDescription": "High bead filler - Maximises steering response, high speed stability and durability.",
      },
      {
        "id": 90,
        "group": 1,
        "pattern": "RH06",
        "featuresTitle": "",
        "featureDescription": "Wide, high-tensile steel belts - Enhances tread strength for steering response and tread wear life.",
      },
      {
        "id": 90,
        "group": 1,
        "pattern": "RH06",
        "featuresTitle": "",
        "featureDescription": "Jointless two-cap ply - Improves uniformity for smooth rides and durability.",
      },
      {
        "id": 90,
        "group": 1,
        "pattern": "RH06",
        "featuresTitle": "",
        "featureDescription": "Rim protector - Provides better protection against outer shock and scratches.",
      },
     
    ]
})

export const getters = {
    selectfeature (state){
        return state.selectfeature
    }
}

export const mutations = {
    SET_SELECT_PATTERN_FEATURE (state, pattern) {
        for (var item, i = 0; item = state.features[i++];) {
            if (pattern == item.pattern) {
                state.selectfeature.push(item);
            }
        }
    },
    SET_CLEAR_FEATURE_SELECTION (state, data) {
        state.selectfeature = data
    },
}

export const actions = {
    async setSelectPattaern ({ commit }, pattern) {
        commit('SET_SELECT_PATTERN_FEATURE', pattern)
    },
    clearSelectFeaturs ({ commit }) {
        commit('SET_CLEAR_FEATURE_SELECTION', [])
    },
}